#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Shuma Suzuki
# SPDX-LIcense-Identifier: BSD-3-Clause

import sys

ans1 = 0
ans2 = 0
ans3 = 0
for line in sys.stdin:

        ans1 += int(line)               #1つずつ足す
        ans2 += int(line) + int(line)   #2重に足す
        ans3 += int(line) * 3           #3倍にして足す

print("合計 =", ans1 )
print("2重に足した値 =", ans2)
print("3重に足した値 =", ans3)
